export const exchangeTypeConfig = {
  sh: '上证',
  sz: '深证',
  index: '板块',
  SH: '上证',
  SZ: '深证',
  INDEX: '板块'
}

export const assetTypeConfig = {
  0: '股票',
  1: '期货',
  2: '期权',
  3: '外汇',
  4: '指数',
  5: '基金',
  6: '债券',
  7: '认购权证',
  8: '认沽权证',
  9: '牛证',
  10: '熊证',
  11: '其他',
};

export const securityTypeConfig = {
  0: '上证A股',
  1: '上证B股',
  2: '上证基金通-货币型',
  3: '上证基金通',
  4: '上证ETF基金',
  5: '上证封闭式基金',
  6: '上证国债、地方债',
  7: '上证企债',
  8: '上证可转债',
  9: '上证债券回购',
  10: '上证指数',
  11: '上证权证',
  12: '上证开放基金',
  13: '上证领先指数',
  14: '上证其他',
  15: '深证指数',
  16: '深证A股',
  17: '深证B股',
  18: '深证基金',
  19: '深证债券',
  20: '深证国债回购',
  21: '深证A股增发转配',
  22: '深证A股权证',
  23: '深证国债现货',
  24: '深证可转换债券',
  25: '深证B股权证',
  26: '深证代办沪市股票',
  27: '深证开放式基金',
  28: '深证领先指数',
  29: '深证创业板',
  30: '深证中小板',
  31: '深证其他',
  32: 'HK',
  33: 'US',
  101: '功能键',
  102: '快捷键',
}

const KeyBoardToolsShowType = [{
  command: 'YEAR',
  type: 'tool-action',
  stockCode: 'YEAR',
  stockName: '年线',
  securityType: 101,
  maps: ['actions-YEAR'],
}, {
  command: 'SEAS',
  type: 'tool-action',
  stockCode: 'SEAS',
  stockName: '季线',
  securityType: 101,
  maps: ['actions-SEAS'],
}, {
  command: 'MONTH',
  type: 'tool-action',
  stockCode: 'MONTH',
  stockName: '月线',
  securityType: 101,
  maps: ['actions-MONTH'],
}, {
  command: 'WEEK',
  type: 'tool-action',
  stockCode: 'WEEK',
  stockName: '周线',
  securityType: 101,
  maps: ['actions-WEEK'],
}, {
  command: 'DAY',
  type: 'tool-action',
  stockCode: 'DAY',
  stockName: '日线',
  securityType: 101,
  maps: ['actions-DAY'],
}, {
  command: 'M1',
  type: 'tool-action',
  stockCode: 'M1',
  stockName: '一分钟线',
  securityType: 101,
  maps: ['actions-M1'],
}, {
  command: 'M5',
  type: 'tool-action',
  stockCode: 'M5',
  stockName: '五分钟线',
  securityType: 101,
  maps: ['actions-M5'],
}, {
  command: 'M15',
  type: 'tool-action',
  stockCode: 'M15',
  stockName: '十五分钟线',
  securityType: 101,
  maps: ['actions-M15'],
}, {
  command: 'M30',
  type: 'tool-action',
  stockCode: 'M30',
  stockName: '三十分钟线',
  securityType: 101,
  maps: ['actions-M30'],
}, {
  command: 'M60',
  type: 'tool-action',
  stockCode: 'M60',
  stockName: '六十分钟线',
  securityType: 101,
  maps: ['actions-M60'],
}]

export const KeyBoardTools = [{
  command: 'clean',
  type: 'tool-func',
  stockCode: 'T00001',
  stockName: '清理缓存',
  securityType: 101,
  maps: ['清理缓存', 'qlhc', 'tools-clean', 'T00001'],
  callBack: (data) => {
    localStorage.clear();
    window.location.reload();
  }
}, {
  command: 'reload',
  type: 'tool-func',
  stockCode: 'T00002',
  stockName: '刷新页面',
  securityType: 101,
  maps: ['刷新页面', 'sxym', 'tools-reload', 'T00002'],
  callBack: (data) => {
    window.location.reload();
  }
}, {
  command: 'sz180',
  type: 'tool-stock',
  stockCode: '180',
  stockName: '上证180',
  securityType: 101,
  maps: ['上证180', 'tools-sz180', '180'],
  uuid: 'SH.000010',
  exchange: "SH",
}, {
  command: 'sz100',
  type: 'tool-stock',
  stockCode: '100',
  stockName: '深证100',
  securityType: 101,
  maps: ['深证100', 'tools-sz100', '100'],
  uuid: 'SZ.399330',
  exchange: "SZ",
}, {
  command: 'hs300',
  type: 'tool-stock',
  stockCode: '300',
  stockName: '沪深300',
  securityType: 101,
  maps: ['沪深300', 'tools-hs300', '300'],
  uuid: 'SH.000300',
  exchange: "SH",
}, {
  command: 'F3',
  type: 'tool-quick',
  stockCode: 'F3',
  stockName: '上证指数',
  securityType: 102,
  maps: ['quicks-F3'],
  uuid: 'SH.000001',
  exchange: "SH",
}, {
  command: 'F4',
  type: 'tool-quick',
  stockCode: 'F4',
  stockName: '深证成指',
  securityType: 102,
  maps: ['quicks-F4'],
  uuid: 'SZ.399001',
  exchange: "SZ",
}, ...KeyBoardToolsShowType];

export const KeyCode = {
  LEFT: 37,
  UP: 38,
  RIGHT: 39,
  DOWN: 40,
  ENTER: 13,
}
